In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_excel("alt_data_730days.xlsx")

In [4]:
print(df.columns)
display(df.head(3))

Index(['times', 'lunar_probe.ElapsedDays', 'lunar_probe.Luna.SMA',
       'lunar_probe.Luna.ECC', 'lunar_probe.LunaFixed.RAAN',
       'lunar_probe.LunaFixed.AOP', 'lunar_probe.Luna.Altitude',
       'lunar_probe.Luna.TA', 'lunar_probe.Luna.Longitude',
       'lunar_probe.Luna.Latitude'],
      dtype='object')

,times,lunar_probe.ElapsedDays,lunar_probe.Luna.SMA,lunar_probe.Luna.ECC,lunar_probe.LunaFixed.RAAN,lunar_probe.LunaFixed.AOP,lunar_probe.Luna.Altitude,lunar_probe.Luna.TA,lunar_probe.Luna.Longitude,lunar_probe.Luna.Latitude
0,1.0,0.000000,1836.805107,0.026315,0.000000,180.000000,50.269050,0.000000,180.0,2.555410e-14
1,2.0,0.002161,1837.010621,0.026415,359.999489,177.485402,50.958913,9.809252,-170.0,-2.611512e-01
2,3.0,0.004326,1836.951725,0.026349,359.955147,175.254577,52.995173,19.526885,-160.0,-5.141464e-01

In [5]:
%matplotlib qt

In [11]:
# plotting altitude for 730 days

x_vals= np.array(df["lunar_probe.ElapsedDays"])
y_vals= np.array(df["lunar_probe.Luna.Altitude"])

plt.figure(1)

plt.plot(x_vals, y_vals)

plt.xlim(0, 730)

plt.title("Altitude of s/c for 730 days", fontsize=22) #  SET according to file opened
plt.xlabel("Days Elapsed", fontsize=22)
plt.ylabel("Altitude in km", fontsize=22)
plt.xticks(size=18)
plt.yticks(size=18)
plt.grid()
plt.show()

In [12]:
# plotting altitude of Apolune and Perilune only


df1= df[(abs(df["lunar_probe.Luna.TA"])> 175) & (abs(df["lunar_probe.Luna.TA"])< 185)]# dataset of values at apolune  only
df2= df[(abs(df["lunar_probe.Luna.TA"])<5) | (abs(df["lunar_probe.Luna.TA"])>355)]# dataset of values at perilune only


df2.head()

x_vals_a= np.array(df1["lunar_probe.ElapsedDays"])
y_vals_a= np.array(df1["lunar_probe.Luna.Altitude"])

x_vals_p= np.array(df2["lunar_probe.ElapsedDays"])
y_vals_p= np.array(df2["lunar_probe.Luna.Altitude"])

plt.figure(2)

plt.plot(x_vals_a, y_vals_a, label= "Apolune", color="Orange")
plt.plot(x_vals_p, y_vals_p, label= "Perilune" ,color= "Blue")

plt.xlim(0, 730)

plt.title("Altitude of Apolune and Perilune for 730 days", fontsize=22) #  SET according to file opened
plt.xlabel("Days Elapsed", fontsize=22)
plt.ylabel("Altitude in km", fontsize=22)
plt.xticks(size=18)
plt.yticks(size=18)
plt.legend()
plt.grid()
plt.show()

In [17]:
# plotting longitude of perilune (=RAAN +AOP) only when s/c is at Apolune or Perilune

df3=pd.concat([df1,df2])
df3=df3.sort_index()


y_vals= np.array(df3["lunar_probe.LunaFixed.RAAN"]+ df3["lunar_probe.LunaFixed.AOP"])

y_vals= np.where(y_vals>360, y_vals-360, y_vals)

x_vals= np.array(df3["lunar_probe.ElapsedDays"])

plt.figure(3)
plt.plot(x_vals, y_vals, label="Longitude of Perilune")
plt.axhline(y=180, color= "red", label="180", linewidth=3)
plt.xlim(0, 730)
plt.ylim(0, 360)

plt.title("Longitude of Perilune for 730 days", fontsize=22) #  SET according to file opened
plt.xlabel("Days Elapsed", fontsize=22)
plt.ylabel("Longitude of Perilune in LunaFixed", fontsize=22)
plt.xticks(size=18)
plt.yticks(size=18)
plt.legend()
plt.grid()
plt.show()

# Getting rid of the horizontal lines when plotting altitude vs longitude in LunaFixed system

### when longitude goes from 180 to -170 or 170 to -180 a horizontal line is added. The idea is to take small arrays of x-y plottable data from dataframe in which longitude value is in strictly increasing order. Corresponding altitude values are the plottable y-values. These x-y values are plotted one array at a time while traversing through full dataset.

In [20]:
x_vals= np.array(df["lunar_probe.Luna.Longitude"])
y_vals= np.array(df["lunar_probe.Luna.Altitude"])

plot_x=np.zeros(0)  # to store plottable values during each orbit... bascially x vals should be in insreasing order
plot_y=np.zeros(0)

plt.figure(4)

for i, long_val in enumerate(x_vals):
    if (abs(long_val)> 175 ):  # to skip horizontal lines when going 170 to -180 or 180 to -170 
        
            
            if (long_val<0): # long value is -ve
                    
                plot_x= np.append(plot_x, -x_vals[i])# add altitude to the positive side
                plot_y= np.append(plot_y, y_vals[i]) 
                    
                plt.plot(plot_x, plot_y, linewidth=.01 ,color="red")     # plot plottable values
                
                plot_x=np.zeros(0)   # dump the array values
                plot_y=np.zeros(0)
                    
                plot_x= np.append(plot_x, x_vals[i])# to the new array add the most negative number
                plot_y= np.append(plot_y, y_vals[i]) 
                    
            else:
                plot_x= np.append(plot_x, x_vals[i])# add a last postitve value
                plot_y= np.append(plot_y, y_vals[i])
                
                plt.plot(plot_x, plot_y, linewidth=.01 ,color="red")     # plot plottable values
                
                plot_x=np.zeros(0)   # dump the array values
                plot_y=np.zeros(0)
                    
                plot_x= np.append(plot_x, -x_vals[i])# to the new array add the most negative number
                plot_y= np.append(plot_y, y_vals[i])
         
        
        
        
    else:
        plot_x= np.append(plot_x, x_vals[i])  # plottable x_values should be in increasing order
        plot_y= np.append(plot_y, y_vals[i])
 

    
#####################################################################


plt.xlim(-180, 180)
plt.xticks(np.arange(-180, 180, 10))
plt.title("Altitude of s/c for 730 days", fontsize=25) #  SET according to file opened
plt.xlabel("Longitude LunaFixed", fontsize=25)
plt.ylabel("Altitude", fontsize=25)
plt.xticks(size=12)
plt.yticks(size=18)
plt.grid()
plt.show()

########################################################################